/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, January 24, 2018 at 12:17:23 AM Eastern European Standard Time
* Operating System: Version 11.1.2 (Build 15B202)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard-Structs.h>
#import <SBScreenEdgePanGestureRecognizer.h>
#import <libobjc.A.dylib/_UISettingsKeyObserver.h>

@class SBHomeGestureSettings, SBFluidSwitcherGestureExclusionTrapezoid, SBTouchHistory, NSString;

@interface SBHomeGesturePanGestureRecognizer : SBScreenEdgePanGestureRecognizer <_UISettingsKeyObserver> {

	BOOL _preventHorizontalSwipesOutsideTrapezoid;
	BOOL _installedAsSystemGesture;
	SBHomeGestureSettings* _homeGestureSettings;
	SBFluidSwitcherGestureExclusionTrapezoid* _portraitExclusionTrapezoid;
	SBFluidSwitcherGestureExclusionTrapezoid* _landscapeExclusionTrapezoid;
	SBTouchHistory* _touchHistory;

}

@property (nonatomic,retain) SBHomeGestureSettings * homeGestureSettings;                                         //@synthesize homeGestureSettings=_homeGestureSettings - In the implementation block
@property (nonatomic,retain) SBFluidSwitcherGestureExclusionTrapezoid * portraitExclusionTrapezoid;               //@synthesize portraitExclusionTrapezoid=_portraitExclusionTrapezoid - In the implementation block
@property (nonatomic,retain) SBFluidSwitcherGestureExclusionTrapezoid * landscapeExclusionTrapezoid;              //@synthesize landscapeExclusionTrapezoid=_landscapeExclusionTrapezoid - In the implementation block
@property (nonatomic,retain) SBTouchHistory * touchHistory;                                                       //@synthesize touchHistory=_touchHistory - In the implementation block
@property (assign,nonatomic) BOOL preventHorizontalSwipesOutsideTrapezoid;                                        //@synthesize preventHorizontalSwipesOutsideTrapezoid=_preventHorizontalSwipesOutsideTrapezoid - In the implementation block
@property (assign,nonatomic) BOOL installedAsSystemGesture;                                                       //@synthesize installedAsSystemGesture=_installedAsSystemGesture - In the implementation block
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (copy,readonly) NSString * description;
@property (copy,readonly) NSString * debugDescription;
-(void)setInstalledAsSystemGesture:(BOOL)arg1 ;
-(SBHomeGestureSettings *)homeGestureSettings;
-(void)setHomeGestureSettings:(SBHomeGestureSettings *)arg1 ;
-(SBTouchHistory *)touchHistory;
-(void)setTouchHistory:(SBTouchHistory *)arg1 ;
-(void)sb_commonInitHomeGesturePanGestureRecognizer;
-(void)_updateHomeGestureParameters;
-(BOOL)_isOutsideOfExclusionTrapezoid;
-(BOOL)_shouldBlockHomeGestureForKeyboardInputMode:(id)arg1 ;
-(void)_setUpExclusionTrapezoids;
-(id)_currentExclusionTrapezoidForEdge:(unsigned long long)arg1 ;
-(void)setPreventHorizontalSwipesOutsideTrapezoid:(BOOL)arg1 ;
-(BOOL)preventHorizontalSwipesOutsideTrapezoid;
-(BOOL)installedAsSystemGesture;
-(SBFluidSwitcherGestureExclusionTrapezoid *)portraitExclusionTrapezoid;
-(void)setPortraitExclusionTrapezoid:(SBFluidSwitcherGestureExclusionTrapezoid *)arg1 ;
-(SBFluidSwitcherGestureExclusionTrapezoid *)landscapeExclusionTrapezoid;
-(void)setLandscapeExclusionTrapezoid:(SBFluidSwitcherGestureExclusionTrapezoid *)arg1 ;
-(id)init;
-(id)initWithTarget:(id)arg1 action:(SEL)arg2 ;
-(void)touchesBegan:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesMoved:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesEnded:(id)arg1 withEvent:(id)arg2 ;
-(void)reset;
-(void)settings:(id)arg1 changedValueForKey:(id)arg2 ;
-(BOOL)_shouldBegin;
-(id)initWithTarget:(id)arg1 action:(SEL)arg2 type:(long long)arg3 maxTouches:(unsigned long long)arg4 ;
-(CGPoint)_locationForTouch:(id)arg1 ;
-(id)initWithTarget:(id)arg1 action:(SEL)arg2 type:(long long)arg3 ;
@end
