/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, January 24, 2018 at 12:17:24 AM Eastern European Standard Time
* Operating System: Version 11.1.2 (Build 15B202)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <UIKit/UIScreenEdgePanGestureRecognizer.h>

@interface SBScreenEdgePanGestureRecognizer : UIScreenEdgePanGestureRecognizer {

	BOOL _shouldUseGrapeFlags;
	double _grabberActiveZoneWidth;

}

@property (assign,nonatomic) double grabberActiveZoneWidth;                                      //@synthesize grabberActiveZoneWidth=_grabberActiveZoneWidth - In the implementation block
@property (assign,nonatomic,__weak) id<SBSystemGestureRecognizerDelegate> delegate; 
@property (assign,nonatomic) BOOL shouldUseGrapeFlags;                                           //@synthesize shouldUseGrapeFlags=_shouldUseGrapeFlags - In the implementation block
-(void)sb_commonInitScreenEdgePanGestureRecognizer;
-(double)grabberActiveZoneWidth;
-(BOOL)isLocationWithinGrabberActiveZone;
-(void)setGrabberActiveZoneWidth:(double)arg1 ;
-(id)initWithTarget:(id)arg1 action:(SEL)arg2 ;
-(void)setShouldUseGrapeFlags:(BOOL)arg1 ;
-(BOOL)shouldUseGrapeFlags;
-(BOOL)_shouldUseGrapeFlags;
-(CGPoint)_locationForTouch:(id)arg1 ;
-(long long)_touchInterfaceOrientation;
-(id)initWithTarget:(id)arg1 action:(SEL)arg2 type:(long long)arg3 ;
@end

