/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, January 24, 2018 at 12:17:24 AM Eastern European Standard Time
* Operating System: Version 11.1.2 (Build 15B202)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

typedef struct CGPoint {
	double x;
	double y;
} CGPoint;

typedef struct __IOHIDEvent* IOHIDEventRef;

typedef struct __CFBoolean* CFBooleanRef;

typedef struct __GSEvent* GSEventRef;

typedef struct {
	BOOL field1;
	BOOL field2;
	BOOL field3;
	BOOL field4;
	BOOL field5;
	double field6;
	int field7;
} SCD_Struct_SB4;

typedef struct _NSZone* NSZoneRef;

typedef struct UIEdgeInsets {
	double top;
	double left;
	double bottom;
	double right;
} UIEdgeInsets;

typedef struct CGSize {
	double width;
	double height;
} CGSize;

typedef struct CGRect {
	CGPoint origin;
	CGSize size;
} CGRect;

typedef struct {
	double value;
	BOOL inclusive;
} SCD_Struct_SB9;

typedef struct {
	SCD_Struct_SB9 start;
	SCD_Struct_SB9 end;
} SCD_Struct_SB10;

typedef struct __CTServerConnection* CTServerConnectionRef;

typedef struct __CFString* CFStringRef;

typedef struct __SCDynamicStore* SCDynamicStoreRef;

typedef struct tcp_connection_fallback_watch_s* tcp_connection_fallback_watch_sRef;

typedef struct {
	int field1;
	int field2;
} SCD_Struct_SB15;

typedef struct CGColor* CGColorRef;

typedef struct {
	double field1;
	double field2;
	BOOL field3;
	BOOL field4;
	double field5;
	double field6;
	double field7;
	double field8;
	double field9;
	double field10;
	double field11;
} SCD_Struct_SB17;

typedef struct {
	unsigned field1;
	unsigned field2;
	unsigned field3;
	unsigned field4;
	unsigned field5;
	int field6;
} SCD_Struct_SB18;

typedef struct {
	unsigned field1;
} SCD_Struct_SB19;

typedef struct {
	SCD_Struct_SB18 field1;
	SCD_Struct_SB19 field2;
} SCD_Struct_SB20;

typedef struct {
	unsigned field1[8];
} SCD_Struct_SB21;

typedef struct __CFDictionary* CFDictionaryRef;

typedef struct {
	long long field1;
	CGPoint field2;
	CGPoint field3;
} SCD_Struct_SB23;

typedef struct NSRange {
	unsigned long long location;
	unsigned long long length;
} NSRange;

typedef struct __CFRunLoop* CFRunLoopRef;

typedef struct __WiFiManagerClient* WiFiManagerClientRef;

typedef struct __WiFiDeviceClient* WiFiDeviceClientRef;

typedef struct __WiFiNetwork* WiFiNetworkRef;

typedef struct {
	float field1;
	__CFArray field2;
	float field3;
} SCD_Struct_SB29;

typedef struct {
	double field1;
	SCD_Struct_SB10 field2;
	long long field3;
} SCD_Struct_SB30;

typedef struct {
	double value;
	SCD_Struct_SB10 interval;
	long long mode;
} SCD_Struct_SB31;

typedef struct BKSDisplayBrightnessTransaction* BKSDisplayBrightnessTransactionRef;

typedef struct {
	unsigned long long field1;
	id field2;
	unsigned long long field3;
	unsigned long long field4[5];
} SCD_Struct_SB33;

typedef struct MGNotificationTokenStruct* MGNotificationTokenStructRef;

typedef struct {
	long long field1;
	long long field2;
	double field3;
} SCD_Struct_SB35;

typedef struct {
	long long startStyle;
	long long endStyle;
	double transitionFraction;
} SCD_Struct_SB36;

typedef struct {
	BOOL valid;
	SCD_Struct_SB36 styleTransitionState;
} SCD_Struct_SB37;

typedef struct {
	BOOL field1;
	SCD_Struct_SB36 field2;
} SCD_Struct_SB38;

typedef struct __CFRunLoopObserver* CFRunLoopObserverRef;

typedef struct {
	unsigned floatingApplicationRootViewController_allowsPresentScreenEdgePanGestureRecognizerForDeviceApplicationSceneHandle : 1;
	unsigned floatingApplicationRootViewController_requiresGrabberTongueForDeviceApplicationSceneHandle : 1;
	unsigned floatingApplicationRootViewController_requiresGrabberTongueOutsideGrabberFreeRegionForDeviceApplicationSceneHandle : 1;
	unsigned floatingApplicationRootViewController_darkenViewTappedForDeviceApplicationSceneHandle : 1;
	unsigned floatingApplicationRootViewControllerDidCompleteDeviceApplicationSceneHandleSuspendAnimation : 1;
} SCD_Struct_SB40;

typedef struct {
	unsigned floatingApplicationController_needsVisibleWindow : 1;
} SCD_Struct_SB41;

typedef struct __CFArray* CFArrayRef;

typedef struct CGAffineTransform {
	double a;
	double b;
	double c;
	double d;
	double tx;
	double ty;
} CGAffineTransform;

typedef struct __IOSurface* IOSurfaceRef;

typedef struct SBNormalizedTransitionInterval {
	double start;
	double duration;
} SBNormalizedTransitionInterval;

typedef struct _CARenderImage* CARenderImageRef;

typedef struct {
	unsigned field1 : 1;
	unsigned field2 : 1;
	unsigned field3 : 1;
	unsigned field4 : 1;
	unsigned field5 : 1;
	unsigned field6 : 1;
	unsigned field7 : 1;
	unsigned field8 : 1;
	unsigned field9 : 1;
	unsigned field10 : 1;
	unsigned field11 : 1;
} SCD_Struct_SB47;

typedef struct {
	BOOL field1[35];
	char field2[64];
	char field3[64];
	int field4;
	int field5;
	char field6[100];
	char field7[100];
	char field8[100];
	char field9[2][1024];
	unsigned field10;
	int field11;
	int field12;
	unsigned field13;
	int field14;
	unsigned field15;
	char field16[150];
	int field17;
	int field18;
	unsigned field19 : 1;
	unsigned field20 : 1;
	unsigned field21 : 1;
	char field22[256];
	unsigned field23 : 1;
	unsigned field24 : 1;
	unsigned field25 : 1;
	unsigned field26 : 1;
	unsigned field27 : 1;
	unsigned field28;
	unsigned field29 : 1;
	unsigned field30 : 1;
	unsigned field31 : 1;
	char field32[256];
	char field33[256];
	char field34[100];
	unsigned field35 : 1;
	unsigned field36 : 1;
	unsigned field37 : 1;
	double field38;
	unsigned field39 : 1;
} SCD_Struct_SB48;

typedef struct CGImage* CGImageRef;

typedef struct {
	unsigned floatingDockRootViewControllerShouldHandlePanGestureRecognizer : 1;
	unsigned floatingDockRootViewControllerShouldBeginScreenEdgeGestureRecognizer : 1;
} SCD_Struct_SB50;

typedef struct {
	CGRect field1;
	CGRect field2;
	CGRect field3;
	CGRect field4;
	CGRect field5;
} SCD_Struct_SB51;

typedef struct AWNotification_s* AWNotification_sRef;

typedef struct SBIconCoordinate {
	long long row;
	long long col;
} SBIconCoordinate;

typedef struct {
	UIEdgeInsets field1;
	CGRect field2;
	CGRect field3;
	CGRect field4;
	CGRect field5;
	double field6;
} SCD_Struct_SB54;

typedef struct {
	BOOL itemIsEnabled[35];
	char timeString[64];
	char shortTimeString[64];
	int gsmSignalStrengthRaw;
	int gsmSignalStrengthBars;
	char serviceString[100];
	char serviceCrossfadeString[100];
	char serviceImages[2][100];
	char operatorDirectory[1024];
	unsigned serviceContentType;
	int wifiSignalStrengthRaw;
	int wifiSignalStrengthBars;
	unsigned dataNetworkType;
	int batteryCapacity;
	unsigned batteryState;
	char batteryDetailString[150];
	int bluetoothBatteryCapacity;
	int thermalColor;
	unsigned thermalSunlightMode : 1;
	unsigned slowActivity : 1;
	unsigned syncActivity : 1;
	char activityDisplayId[256];
	unsigned bluetoothConnected : 1;
	unsigned displayRawGSMSignal : 1;
	unsigned displayRawWifiSignal : 1;
	unsigned locationIconType : 1;
	unsigned quietModeInactive : 1;
	unsigned tetheringConnectionCount;
	unsigned batterySaverModeActive : 1;
	unsigned deviceIsRTL : 1;
	unsigned lock : 1;
	char breadcrumbTitle[256];
	char breadcrumbSecondaryTitle[256];
	char personName[100];
	unsigned electronicTollCollectionAvailable : 1;
	unsigned wifiLinkWarning : 1;
	unsigned wifiSearching : 1;
	double backgroundActivityDisplayStartDate;
	unsigned shouldShowEmergencyOnlyStatus : 1;
} SCD_Struct_SB55;

typedef struct SBWindowLevelRange_struct {
	double start;
	double end;
} SBWindowLevelRange_struct;

